### ISSUE TITLE
Thanks.

### ISSUE THREAD

**Issue by Feathur** [sameer-shelavale/php-countries-array#2]
That's all. You should put a donate button up.

**Comment by sameer-shelavale** [comment]
Thank you very much for your appreciation, but I am not sure if that will violate the github ToS.
For now you may send donations directly to my email samiirds[AT]gmail.com.

**Comment by Feathur** [comment]
I sent a small donation. Nothing in the TOS for github prevents you from having a donate button or link in your readme.

**Comment by sameer-shelavale** [comment]
Thank you.
