### ISSUE TITLE
Missing / wrong entries

### ISSUE THREAD

**Issue by zulus** [sameer-shelavale/php-countries-array#6]
Hi I found three missing/wrong entries:
Uruguay - should be URY, URU in your map
Virgin Islands, British - should be VGB, missing in your map
Romania - should be ROU, ROM in your map (code was changed in 2002)

Based on https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

**Comment by terrymun** [comment]
I think the ROU/ROM change was already addressed in an earlier pull request.

**Comment by zulus** [comment]
Argh yes, I wrote comment based on stable version.

**Comment by sameer-shelavale** [comment]
hi guys,
I have created a new release 1.0.3 which includes all the bug fixes since 1.0.2.
It was long overdue actually.
Thank you for your efforts to improve the package.
